---
kind: pipeline
type: kubernetes
name: default
steps:
- name: restore cache
  image: harbor.xirion.net/hub/plugins/s3-cache
  settings:
    pull: true
    endpoint: http://192.168.0.112:9000
    root: drone
    restore: true
    access_key:
      from_secret: MINIO_ACCESS_KEY
    secret_key:
      from_secret: MINIO_SECRET_KEY
- name: test rust
  image: harbor.xirion.net/library/rust-gcc
  commands:
  - export CARGO_HOME="$PWD/.cargo"
  - echo $CARGO_HOME
  - cargo test

- name: rebuild cache
  image: harbor.xirion.net/hub/plugins/s3-cache
  settings:
    pull: true
    root: drone
    endpoint: http://192.168.0.112:9000
    access_key:
      from_secret: MINIO_ACCESS_KEY
    secret_key:
      from_secret: MINIO_SECRET_KEY
    rebuild: true
    mount:
      - target/
      - .cargo/
    when:
      event: push
