[package]
name = "dsmr"
version = "0.1.0"
authors = ["Victor Roest <victor@xirion.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dsmr5 = { path = "../dsmr5" }
serial = "0.4.0"
paho-mqtt = "0.9.1"
