[package]
name = "dsmr"
version = "0.1.0"
authors = ["Victor Roest <victor@xirion.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dsmr5 = { git = "https://github.com/NULLx76/dsmr5" }
serial = "0.4.0"
paho-mqtt = "0.9.1"
sentry = "0.21"
thiserror = "1.0"
